version: '3.7'

#网络配置
networks:
  net:
    external: true
    name: ${PROJECT_NETWORK}

services:
  #主服务
  digital-avatar-web:
    # 镜像名称
    image: hci/java17
    container_name: ${CONTAINER_PREFIX}-web-ms
    restart: always
    depends_on:
      - digital-avatar-web-redis
    networks:
      net:
    # 端口映射
    ports:
      - 9002:8080
    # 挂载目录
    volumes:
      - /etc/localtime:/etc/localtime
      - ./files:/app/files
      - ./app/tmp:/app/tmp
      - ./app/cache:/app/cache
      - ./app/logs:/app/logs
      - ./app/config-file:/app/config-file
      - ./app/config.yml:/app/config.yml
      - ./app/digital-avatar-ws-0.0.1-fat.jar:/app/digital-avatar-web-ms.jar
    entrypoint:
      - java
      - -Xmx4G
      - -Xms2G
      - -XX:+UseG1GC
      - -Duser.timezone=GMT+8
      - -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory
      - -jar
      - digital-avatar-web-ms.jar
      - -c
      - config.yml


  digital-avatar-web-redis:
    image: redis:latest
    container_name: ${CONTAINER_PREFIX}-web-redis
    restart: always
    networks:
      net:
    volumes:
      - ./redis-data:/data
    command: redis-server